# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3'

# Define services
services:
  # message:
  #   image: golang:1.20-alpine
  #   container_name: go_app
  #   working_dir: /app
  #   volumes:
  #     - ./message/:/app
  #   ports:
  #     - "8080:8080"
  #   command: sh -c "go run app.go"
  #   depends_on:
  #     - postgres
  #   environment:
  #     DB_PORT: ${POSTGRES_PORT}
  #     DB_HOST: postgres_database

  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_USER: ${POSTGRES_USER}
  redis:
    image: redis:latest
    container_name: redis_server
    restart: always
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro  # Monte le fichier de configuration en lecture seule
    environment:
      - REDIS_PORT=6379

  # user:
  #   image: 'bitnami/symfony:6.2.6-debian-11-r2'
  #   ports:
  #     - '8000:8000'
  #   volumes:
  #     - './:/app'
  #   environment:
  #     - SYMFONY_PROJECT_NAME=securedWhisker

  #     - DATABASE_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_database:${POSTGRES_PORT}/${POSTGRES_DB}?serverVersion=16&charset=utf8"
  #   depends_on:
  #     - postgres_database

  # postgres_database:
  #   image: postgres:15-alpine
  #   restart: unless-stopped
  #   ports:
  #     - ${POSTGRES_PORT}
  #   environment:
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #   volumes:
  #     - database_data:/var/lib/postgresql/data:rw
      
volumes:
  database_data:
  redis_data: