FROM composer

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier les fichiers de l'application dans le conteneur
COPY ./user /app
COPY .env /app

# Installer les dépendances Symfony
RUN composer install --no-interaction --optimize-autoloader

# Exposer le port 8000
EXPOSE 8000

# Commande par défaut pour exécuter le serveur Symfony
CMD ["php", "-S", "0.0.0.0:8000", "-t", "./public"]