name: Deploy

on:
  push:
    branches:
      - beta

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{secrets.ip}} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          
      - name: Checkout du dépôt
        uses: actions/checkout@v4
        with:
          ref: beta

      - name: Démarrer l'agent SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Mettre à jour le dépôt distant
        run: ssh debian@${{ secrets.ip }} "cd ~/SecuredWhisker && git pull origin beta"

      - name: Redémarrage du docker
        run: ssh debian@${{secrets.ip}} "cd ~/SecuredWhisker && sudo docker compose up -d --build --force-recreate"