name: Lint - NextJS

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  
  security-check-nextjs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        working-directory: ./front
        run: npm ci

      - name: Lint code
        working-directory: ./front
        run: npm run lint