name: Dependency Security Check - NextJS

on:
  schedule:
    - cron: "0 19 * * 4"
    
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

jobs:
  
  security-check-nextjs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./front
        run: npm ci

      - name: Audit dependencies
        working-directory: ./front
        run: npm audit --audit-level=high --production