name: Security Check for Symfony API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, intl, pdo, curl, dom
          tools: composer
          coverage: none

      - name: Install dependencies
        working-directory: ./user
        run: composer install --no-scripts --no-progress --prefer-dist

      - name: Check for vulnerabilities
        working-directory: ./user
        run: composer audit --locked