name: Go Dependency Security Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23' # Spécifiez la version Go que vous utilisez

      - name: Install govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Download dependencies
        working-directory: ./message
        run: |
          go mod tidy
          go mod download

      - name: Analyze dependencies with govulncheck
        working-directory: ./message
        run: |
          govulncheck ./...

      - name: Upload govulncheck results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: vulncheck-results
          path: govulncheck-report.txt

      - name: Display govulncheck results
        run: cat govulncheck-report.txt
