name: Go Dependency Security Check

on:
  workflow_dispatch: # Permet d'exécuter le workflow manuellement
  schedule:
    - cron: "0 2 * * 0" # Planification hebdomadaire, chaque dimanche à 2h du matin
  push:
    branches:
      - main
  pull_request:

jobs:
  dependency-check:
    name: Check Go Dependencies for Security Issues
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21" # Remplacez par la version de Go utilisée dans votre projet

      - name: Install Dependencies
        working-directory: ./message
        run: |
          go mod tidy

      - name: Run Govulncheck on Dependencies
        working-directory: ./message
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...
