name: Dependency Security Check - Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23' # Spécifiez la version Go que vous utilisez

      - name: Install govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Download dependencies
        working-directory: ./message
        run: |
          go mod tidy
          go mod download

      - name: Analyze dependencies with govulncheck
        working-directory: ./message
        run: |
          govulncheck ./...
