name: Go Dependency Security Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23' # Utilisez la version Go de votre choix

      - name: Download dependencies
        working-directory: ./message
        run: |
          go mod tidy
          go mod download

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./message/...
